### ISSUE TITLE
error when trying to use the default makefile command

### ISSUE THREAD

**Issue by BirdSheep** [Yackerw/StarDust-DS#3]
I'm really new to this whole coding and github thing so forgive me if this sucks but Ill try my best.

I'm using windows and I reinstalled devkitpro and stardust but I keep getting the same error about "calico.h" not existing. I've using msys2 and cmd and they both give the same error.

barr3@DESKTOP-2LKK0S6 MSYS ~
$ cd /opt/devkitpro/StarDust-DS-main/source

barr3@DESKTOP-2LKK0S6 MSYS /opt/devkitpro/StarDust-DS-main/source
$ make
make -C arm7
make[1]: Entering directory '/opt/devkitpro/StarDust-DS-main/source/arm7'
main.c
In file included from C:/devkitPro/StarDust-DS-main/source/arm7/source/main.c:1:
C:/devkitPro/libnds/include/nds.h:222:2: error: #error "This header file is only for NDS ARM9 or ARM7"
  222 | #error "This header file is only for NDS ARM9 or ARM7"
      |  ^~~~~
C:/devkitPro/libnds/include/nds.h:225:10: fatal error: calico.h: No such file or directory
  225 | #include <calico.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:39: main.o] Error 1
make[1]: *** [Makefile:91: build] Error 2
make[1]: Leaving directory '/opt/devkitpro/StarDust-DS-main/source/arm7'
make: *** [Makefile:34: checkarm7] Error 2

**Comment by Yackerw** [comment]
Try making sure your libnds is updated to 2.0 properly. Follow the guide to updating via msys2 here.
https://devkitpro.org/wiki/devkitPro_pacman

**Comment by BirdSheep** [comment]
I couldnt find anything about msys2 for updating it on windows but I used the included update installer thingie and it seemed to fix the issue. 
However, a new smaller issue has arisen:

barr3@DESKTOP-2LKK0S6 MSYS /opt/devkitpro/StarDust-DS-main/source
$ make
make -C arm7
make[1]: Entering directory '/opt/devkitpro/StarDust-DS-main/source/arm7'
make[2]: '/opt/devkitpro/StarDust-DS-main/source/arm7/StarDustDS.elf' is up to date.
make[1]: Leaving directory '/opt/devkitpro/StarDust-DS-main/source/arm7'
make -C arm9
make[1]: Entering directory '/opt/devkitpro/StarDust-DS-main/source/arm9'
make[2]: '/opt/devkitpro/StarDust-DS-main/source/arm9/StarDustDS.elf' is up to date.
make[1]: Leaving directory '/opt/devkitpro/StarDust-DS-main/source/arm9'
make: *** No rule to make target 'nitrofiles', needed by 'StarDustDS.nds'.  Stop.

**Comment by Yackerw** [comment]
Ah, right, make a 'nitrofiles' folder. That's something I keep forgetting to fix because git doesn't let you have an empty folder.

**Comment by BirdSheep** [comment]
That seemed to do the trick! Thanks! :D
